### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by Scharfi** [dice-group/PYKE#1]
What are the data formats that PYKE can handle ?
Can you please document that so Its more clearer to know what are all the possible input formats for PYKE.

**Comment by Demirrr** [comment]
Hello Salma,

Currently, Parser Class only accepts N3 and N-Quads. As you may see 23-25.th line in execute.py
```
# For N-Quads, please set ut.triple=4. By default ut.triple=3 as KG is N3.
#ut.triple = 3
```
That being said, you may want to take a look at [https://github.com/RDFLib] to handle KGs with different RDF formats.
