### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Scharfi** [dice-group/PYKE#2]
I am using Windows system and while creating the env from the environment.yml file I run through this issue in the picture. It seemed that this packages are for linux system.
Can you please clarify the configuration settings
![pykeissue](https://user-images.githubusercontent.com/31705416/79917085-1f7d0000-842a-11ea-8d1f-16d6bc99c07a.PNG)

**Comment by Demirrr** [comment]
Hi,

Searching "resolvepackagenotfound" in google would have easily solved your problem [https://github.com/datitran/object_detector_app/issues/41]. This issue stems from the conda installation on different operating systems. 

Please pull the new .yml file from repo. If problem seem to persist, please install packages via pip.
